# Generated by Django 2.2.27 on 2022-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'IP黑名单',
                'verbose_name_plural': 'IP黑名单',
                'db_table': 'monitor_ipblacklist',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
            ],
            options={
                'verbose_name': '在线用户',
                'verbose_name_plural': '在线用户',
                'db_table': 'monitor_onlineusers',
                'ordering': ['-id'],
            },
        ),
    ]
